### ISSUE TITLE
Stateful authentication using JS-cookie

### ISSUE THREAD

**Issue by greenspray9** [PaulC91/shinyauthr#10]
First off, would like to thank you for putting all the work in this package. It has made my life simpler.

However, there is always room for improvement and one problem I noticed that I have to re-login in every new window because currently the package doesn't store successful authentication persistently across tabs so want propose a feature : Would anyone be up for collaboration to combine [cookie.js](https://github.com/js-cookie/js-cookie) to save session-id per user as Cookie with a custom expiry period such that the same user is not required to login again in that time period. 

[This](https://calligross.de/post/using-cookie-based-authentication-with-shiny/) blog uses this cookie.js and exemplifies its usage in R.

**Comment by PaulC91** [comment]
Hi @greenspray9, I think this would definitely been a good feature addition. Unfortunately this is not my area of expertise and I won't have time to look into in the near future but if you would like to give it a go yourself a PR would be very welcome!

Thanks,
Paul

**Comment by greenspray9** [comment]
I will see what I can do and keep you posted.

**Comment by PaulC91** [comment]
This is now a feature thanks to #41
