### ISSUE TITLE
Press return to connect

### ISSUE THREAD

**Issue by MZellou** [PaulC91/shinyauthr#11]
Hello,

I'm trying to implement the return key that triggers the connect button in a Shiny app. I saw what you did using some js here (https://gist.github.com/PaulC91/bd5035875305dfad504f1a3794233186). 
So I tried to connect both methods but unsuccessfully ...

Here is the jQuery code I used : 

```
$(document).keyup(function(event) {
    if ($("#id").is(":focus") && (event.keyCode == 13)) {
        $("#button").click();
    }
});
```
I think that as the id is namepaces in the loginUI, this method won't work.
Any idea ? :)

Thank you in advance,
Marouane

**Comment by PaulC91** [comment]
If you give setup `loginUI` like so `shinyauthr::loginUI(id = "login")` then the IDs you need to target are `#login-password` and `#login-button`:

```
$(document).keyup(function(event) {
    if ($("#login-password").is(":focus") && (event.keyCode == 13)) {
        $("#login-button").click();
    }
});
```

**Comment by MZellou** [comment]
Thank you very much !
