### ISSUE TITLE
Error in execution of Shinyauthr_example app

### ISSUE THREAD

**Issue by mdumer** [PaulC91/shinyauthr#15]
Hi, Hope you are doing well. 
I am trying to execute your example (shinyauthr_example). After execution, it becomes closed and generated an error of 

Warning: Error in : in shinyauthr::login module call. Argument hashed is deprecated. shinyauthr now uses the sodium package for password hashing and decryption. If you had previously hashed your passwords with the digest package to use with shinyauthr, please re-hash them with sodium and use the sodium_hashed argument instead for decryption to work. Sorry for this breaking change but sodium hashing provides added protection against brute-force attacks on stored passwords.

 54: stop
 53: module
 48: callModule
 47: server [C:\shiny-examples\shinyauthr_example/app.R#43]

Error : in shinyauthr::login module call. Argument hashed is deprecated. shinyauthr now uses the sodium package for password hashing and decryption. If you had previously hashed your passwords with the digest package to use with shinyauthr, please re-hash them with sodium and use the sodium_hashed argument instead for decryption to work. Sorry for this breaking change but sodium hashing provides added protection against brute-force attacks on stored passwords. 

Thanks,

**Comment by PaulC91** [comment]
sorry forgot to update the code in the example app. the argument is now called `sodium_hashed` rather than `hashed` so if you change that in the `shinyauthr::login()` function it should work. Or just re-install the package as I've just fixed it on github. thanks.
