### ISSUE TITLE
Application restart required for login after a signup

### ISSUE THREAD

**Issue by SNaveenMathew** [PaulC91/shinyauthr#19]
I'm trying to add signup functionality. I'm using the prescribed code for login verification:

```
credentials <- callModule(
    module = shinyauthr::login,
    id = "login", 
    data = user_base,
    user_col = user,
    pwd_col = password_hash,
    sodium_hashed = TRUE,
    log_out = reactive(logout_init()))
```

In the above code, `user_base` is a global variable. I tried to use `reactive()` and `eventReactive()` to replace the `data`, but got the following error:

> Error in UseMethod("tbl_vars") : 
>   no applicable method for 'tbl_vars' applied to an object of class "c('reactiveExpr', 'reactive')"

Refreshing the page does not help, but I'm able to login with the previously created user after restarting the application (because global variable `user_base` gets updated). But I'm unable to login with any user ID that's created in the current session.

**Desired output:**

On click of signup, a new row gets added to `user_base` during the same session. Login attempt should be successful with the new user.

**Comment by SVPA-PeterTat** [comment]
I'm having the same issue as describe here.  Was there a workaround / solution for this?

**Comment by SNaveenMathew** [comment]
This did not solve my the issue! This may be because I added a 'Signup' tab next to the 'Login' tab that has shinyauthr::loginUI body. I forced a page refresh using JS:
shinyjs::js$refresh()

**Comment by stantond11** [comment]
Have you had a look at the Tychobra/Polished repo? its authentication for shiny and i would recommend it

**Comment by SNaveenMathew** [comment]
That's a great package @stantond11. For now I'm going to stick to shinyauthr + forced shinyjs::js$refresh() even though the signup-signin combo is overly complicated without a page refresh.
