### ISSUE TITLE
shinyauthr in windows

### ISSUE THREAD

**Issue by chitemerere** [PaulC91/shinyauthr#21]
Hi Paul, i have issues with installing shinyauthr in Windows.  I am getting the following error message:

> devtools::install_github("paulc91/shinyauthr")
Downloading GitHub repo paulc91/shinyauthr@master
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 3.5 from http://cran.r-project.org/bin/windows/Rtools/.
√  checking for file 'C:\Users\Stratdigm\AppData\Local\Temp\Rtmp0KSrsU\remotesb41a3f7bec\PaulC91-shinyauthr-6830f43/DESCRIPTION' (381ms)
-  preparing 'shinyauthr':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'shinyauthr_0.0.99.tar.gz'
   
Installing package into ‘\\Mac/Home/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
'\\Mac\Home\Documents'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
* installing *source* package 'shinyauthr' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in findpack(package, lib.loc) : 
  there is no package called 'shinyauthr'
Calls: <Anonymous> -> findpack
Execution halted
ERROR: lazy loading failed for package 'shinyauthr'
* removing '\\Mac/Home/Documents/R/win-library/3.6/shinyauthr'
Error: Failed to install 'shinyauthr' from GitHub:
  (converted from warning) installation of package ‘C:/Users/STRATD~1/AppData/Local/Temp/Rtmp0KSrsU/fileb42aea35df/shinyauthr_0.0.99.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

**Comment by PaulC91** [comment]
try installing Rtools as it suggests?

**Comment by chitemerere** [comment]
Noted with thanks

**Comment by chitemerere** [comment]
I have installed Rtools but still get the following errror message:

> devtools::install_github("paulc91/shinyauthr")
Downloading GitHub repo paulc91/shinyauthr@master
√  checking for file 'C:\Users\Stratdigm\AppData\Local\Temp\Rtmp0KSrsU\remotesb4436b7d11\PaulC91-shinyauthr-6830f43/DESCRIPTION' (403ms)
-  preparing 'shinyauthr':
√  checking DESCRIPTION meta-information ... OK
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'shinyauthr_0.0.99.tar.gz'
   
Installing package into ‘\\Mac/Home/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
'\\Mac\Home\Documents'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
* installing *source* package 'shinyauthr' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in findpack(package, lib.loc) : 
  there is no package called 'shinyauthr'
Calls: <Anonymous> -> findpack
Execution halted
ERROR: lazy loading failed for package 'shinyauthr'
* removing '\\Mac/Home/Documents/R/win-library/3.6/shinyauthr'
Error: Failed to install 'shinyauthr' from GitHub:
  (converted from warning) installation of package ‘C:/Users/STRATD~1/AppData/Local/Temp/Rtmp0KSrsU/fileb424195b3d/shinyauthr_0.0.99.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
