### ISSUE TITLE
login status lose after refreshed

### ISSUE THREAD

**Issue by haodong** [PaulC91/shinyauthr#27]
The newest version.
Each user would lose their login information once refreshed the page.

**Comment by PaulC91** [comment]
This has always been the case. The login is processed as part of the shiny session. If you refresh the page the session is lost.

**Comment by haodong** [comment]
Dear @PaulC91 , I fount [this demo](https://shiny.rstudio.com/gallery/authentication-and-database.html) works fine with refresh!

**Comment by PaulC91** [comment]
It requires the use of browser cookies. May be implemented into shinyauthr in the future but I don't have the time right now sorry!

**Comment by haodong** [comment]
That's OK. I've seen the light.

**Comment by PaulC91** [comment]
Interesting. Care to share your vision?

**Comment by haodong** [comment]
During this year, I saw R was shown in the Top 20 within many so-called "programming language rank"s. 

With the powerful packages around shiny, R-things may become one of the easiest toolboxes to enable data scientists to create specific functional systems in order to do data research.

Take this shinyauthr for example, one can quickly build a customized ERP-liked module in some small circumstances. This would be yet another milestone!
