### ISSUE TITLE
Cant not Install the package "shinyauthr"

### ISSUE THREAD

**Issue by Mero928** [PaulC91/shinyauthr#29]
I cant install the Package "shinyauthr" using the below line 
remotes::install_github("paulc91/shinyauthr")

I got the following Error:
Downloading GitHub repo paulc91/shinyauthr@master
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/paulc91/shinyauthr/tarball/master'

Any advice, 
Amr

**Comment by PaulC91** [comment]
Are you trying from inside a company firewall? sometimes they will not allow downloads from github.

**Comment by Mero928** [comment]
yes, I used my work station but i can download zip file from github but when i use the zip file for the installing it is not working neither.

**Comment by Mero928** [comment]
Now, I could install the package using the following :

install.packages("~/Documents/R/PaulC91-shinyauthr-ea10bfd.tar.gz", repos = NULL, type = "source")

Thank you so much Paul, your prompt response is highly appreciated and thank you for the library

**Comment by PaulC91** [comment]
No problem! Glad you got it sorted.
