### ISSUE TITLE
Tests are needed

### ISSUE THREAD

**Issue by andodet** [PaulC91/shinyauthr#30]
Thanks a lot for the package, with some basic db logic to store/retrieve user credentials it has become my go-to to implement basic auth in Shiny.

I think unit tests are needed to guard the package from bugs, [`testthat`][1] is probably your best go-to on this one.

[1]: https://testthat.r-lib.org/

**Comment by PaulC91** [comment]
Thanks, glad you find the package useful. I want to submit to CRAN at some point and was planning to add some tests before doing that. I don't have a lot of spare time at the moment though so PRs would be very welcome!

**Comment by andodet** [comment]
Added a few basic tests in [this](https://github.com/PaulC91/shinyauthr/pull/31) pull request.

**Comment by PaulC91** [comment]
closed with #52
