### ISSUE TITLE
Additional info in the login box

### ISSUE THREAD

**Issue by aavanesy** [PaulC91/shinyauthr#38]
Hi,

I am using the package and it works just perfect, thank you a lot.

Is there an option to add some extra HTML under the login menu?

![image](https://user-images.githubusercontent.com/48486871/92330097-2c893d00-f021-11ea-84cc-bb2eb5b26631.png)

Something like: **if you forgot your password please contact us at admin@gmail.com**

To be just under or somewhere on this screen.

Thank you

**Comment by PaulC91** [comment]
Hey nice idea. Just added an `additional_ui` argument to `loginUI()` that will add extra UI elements below the login button, if supplied, like so:
```
loginUI(id = "login", additional_ui = tags$p("some more information here", class = "text-center"))
```
If you want to add more than one element wrap them all in `tagList()`. 

Let me know if that's what you were looking for! (you'll need to reinstall the package first)

**Comment by aavanesy** [comment]
Hi,

I will test this shortly and revert.

Thank you a lot!

**Comment by aavanesy** [comment]
Works perfect.
Used `span('test', style = 'color:red;')`
