### ISSUE TITLE
Background and text colour

### ISSUE THREAD

**Issue by p-schaefer** [PaulC91/shinyauthr#39]
Hello,

 I'm wondering if its possible to change the background and text colour for the login UI.

I tried using the additional_ui parmeter with div(style = "background-color: lightblue;"), but that didn't seem to work. 

Thanks!

**Comment by PaulC91** [comment]
Hey,

The login panel has a bootstrap CSS class of `well` so you can re-style it with CSS using this class.

For example adding the following CSS to your app would change the background colour of the login well-panel to black and the font colour to white.

```css
.well {
  background-color: black;
  color: white;
}
```

[See this article](https://shiny.rstudio.com/articles/css.html) for various methods of adding custom CSS to a shiny app.
