### ISSUE TITLE
Customize Shinyauthr LoginUI

### ISSUE THREAD

**Issue by mueedahmed1** [PaulC91/shinyauthr#4]
how to customize the shinyauthr loginUI??

**Comment by PaulC91** [comment]
You can customise all the text elements via the function arguments. If you want a completely custom login UI then I would recommend modifying the [`loginUI` code](../blob/master/R/login.R) to create your own `loginUI` function and using that instead of the package version.

**Comment by PaulC91** [comment]
Going to close this. Will re-open if you get back in touch and don't think my answer is suffice.
