### ISSUE TITLE
CRAN submission

### ISSUE THREAD

**Issue by GitHunter0** [PaulC91/shinyauthr#43]
Hey @PaulC91 , congratulations for `shinyauthr`, it is a very useful package!

Do you plan to submit to CRAN? It would be nice because it would facilitate the access and also be covered by RStudio Package Manager.

Thank you

**Comment by GitHunter0** [comment]
Great news!

**Comment by PaulC91** [comment]
@GitHunter0 now on CRAN: https://cran.r-project.org/package=shinyauthr :)
