### ISSUE TITLE
How to enable password coding by setting "sodium_hashed" parameter?

### ISSUE THREAD

**Issue by andirey** [PaulC91/shinyauthr#44]
Hi, Paul!

Thank you for the great package.

A small issue. I tried to set the parameter "sodium_hashed = TRUE" as you described in the package description:

```
credentials <- callModule(shinyauthr::login, "login", 
                          data = user_base, user_col = user, pwd_col = password,
                          sodium_hashed = TRUE,
                          log_out = reactive(logout_init()))

```

And, get an error as it seems this parameter is not in the list of available parameters.

Maybe there is some method how to protect passwords or how to change the default value for "sodium_hashed" parameter?

Thanks!

Andrii

**Comment by nicholaelaw** [comment]
I use `sodium_hashed = T` and I haven’t run into this issue. Perhaps reinstall the package?

**Comment by PaulC91** [comment]
Closing this. Let me know if you're still having issues and I will re-open.
