### ISSUE TITLE
Error object 'js' not found

### ISSUE THREAD

**Issue by nikosbosse** [PaulC91/shinyauthr#47]
Since the latest update I'm getting two errors when trying to start my app: 
```
Warning: Error in <observer:observeEvent(log_out())>: object 'js' not found
  [No stack trace available]
Warning: Error in shiny::isTruthy: object 'js' not found
  [No stack trace available]
```
I assume I'm doing something unintended, as your example app works without a problem. Happy to try and dig further, I was just hoping maybe you would have a quick idea of what might be going on. Thank you very much!

**Comment by PaulC91** [comment]
@michael-dewar any idea?

**Comment by michael-dewar** [comment]
@nikosbosse Do you have `library(shinyjs)` at the top of your app.R?  Also, is `shinyjs::useShinyjs()` called before the `shinyauthr` module UI?

It seems like `library(shinyjs)` must be called explicitly and it is not enough to rely on `shinyjs::`.  I do not know why.

**Comment by nikosbosse** [comment]
Thanks a lot for your quick response! So calling `library(shinyjs)` in the app script works. 

I'm running my app with golem by calling `run_app()`. I tried adding shinyjs to the namespace of my pacakge, but that didn't work. This is a bit unfortunate as users than have to load my package as well as shinyjs and it is not immediately obvious they would need to load a package that is not loaded when they load my package. Not a big problem, but maybe worth investigating further. 

For now it works :) Thanks a lot for your kind help!

**Comment by PaulC91** [comment]
Does it work if you add `library(shinyjs)` inside your `run_app()` function?

**Comment by nikosbosse** [comment]
Hm it's probably not ideal to call `library()` from within an exported function of a package. Haven't tried that, but I can give it a try and report back

**Comment by PaulC91** [comment]
or try adding shinyjs to the `Depends` list in your `DESCRIPTION` file:

```
Depends:
    shinyjs
```

I think this should load the whole shinyjs package whenever your own packages is loaded.

**Comment by michael-dewar** [comment]
I found the problem and just submitted a PR for the fix.  I was unsuccessful at getting GitHub to link the PR to this issue.

Basically the problem was that I mistakenly used an object `js` from `shinyjs` without the `shinyjs::`.  Sorry about that.

**Comment by nikosbosse** [comment]
Awesome! Thank you very much for your quick help. Much appreciated
