### ISSUE TITLE
Merge with modalDialog

### ISSUE THREAD

**Issue by alexsilve** [PaulC91/shinyauthr#6]
Hi Paul,
I am trying to configure your logout.R to add a pop-out window. What I want to achieve is to transfer current log-out button to a modal button and then logout by activating an actionbutton added to modalDialog. But what I got is a pop-out window when log-in. 
Could you tell me which part I should change? I must added to the wrong location.

Thanks a lot.

**Comment by PaulC91** [comment]
Hi. I won't be able to help without seeing any of your code. If you could post a minimal example I'll try and diagnose the issue. Thanks.

**Comment by alexsilve** [comment]
thanks for your reply. I used a work-around. Basically I edit modalDialog footer as
      footer = tagList(shiny::actionButton("logout-button", "Yes", class = "btn-danger", style = "color: white;")
  in shiny server and add 
observeEvent(input$"logout-button",{
removeModal()
})

Anyway, a great package. Really help me a lot.
Thanks again.

**Comment by PaulC91** [comment]
Glad to hear you found a solution and thanks for the kind words!
