### ISSUE TITLE
Where should I put the data for my own app in shinyboard？

### ISSUE THREAD

**Issue by baoyulinn** [PaulC91/shinyauthr#64]
Where should I put the data for my own app? And I find that through the sidebar, the user can access the data directly and it doesn't block it.

`library(shinydashboard)
library(dplyr)
library(shinycssloaders)
library(shinyWidgets)
library(shinyauthr)
library(shinyjs)

cookie_expiry <- 7
user_base <- data.frame(
  user = c("user1", "user2"),
  password = c("pass1", "pass2"), 
  permissions = c("admin", "standard"),
  name = c("User One", "User Two"),
  stringsAsFactors = FALSE
)

get_sessions_from_db <- function(conn = db, expiry = cookie_expiry) {
  dbReadTable(conn, "sessions") %>%
    mutate(login_time = ymd_hms(login_time)) %>%
    as_tibble() %>%
    filter(login_time > now() - days(expiry))
}

add_session_to_db <- function(user, sessionid, conn = db) {
  tibble(user = user, sessionid = sessionid, login_time = as.character(now())) %>%
    dbWriteTable(conn, "sessions", ., append = TRUE)
}

db <- dbConnect(SQLite(), ":memory:")
dbCreateTable(db, "sessions", c(user = "TEXT", sessionid = "TEXT", login_time = "TEXT"))

user_base <- tibble(
  user = c("user1", "user2"),
  password = c("pass1", "pass2"),
  password_hash = sapply(c("pass1", "pass2"), sodium::password_store),
  permissions = c("admin", "standard"),
  name = c("User One", "User Two")
)

ui <- dashboardPage(
  
  dashboardHeader(
    title = "abc",
    tags$li(
      class = "dropdown",
      style = "padding: 8px;",
      shinyauthr::logoutUI("logout")
    ),
    
    dropdownMenu(
      type = "messages",
      badgeStatus = NULL,
      messageItem("Feedback and suggestions",
                  "qwe",
                  href = "qwe")
    )
  ),
  
  dashboardSidebar(
    collapsed = TRUE,
    div(textOutput("welcome"), style = "padding: 20px"),
    searchInput(
      inputId = "gene",
      label = "abcd",
      placeholder = "Potential Gene",
      value = "abcd",
      btnSearch = icon("search"),
      width = "100%"
    ),
    sidebarMenu(
      menuItem(
        "Potential function of the gene",
        tabName = "page1",
        icon = icon("compass")
      ),
      menuItem(
        "Tips for 123 figures",
        tabName = "page2",
        icon = icon("list")
      ),
      menuItem(
        "Gene for adult sample",
        tabName = "page3",
        icon = icon("lightbulb")
      )
    )
  ),
  
  
  dashboardBody(
    shinyauthr::loginUI(
      "login", 
      cookie_expiry = cookie_expiry, 
      additional_ui = tagList(
        tags$p("test the different outputs from the sample logins below
             as well as an invalid login attempt.", class = "text-center"),
        HTML(knitr::kable(user_base[, -3], format = "html", table.attr = "style='width:100%;'"))
      )
    ),
    tabItems(
    tabItem(tabName = "page1",
            fluidRow(
              valueBoxOutput("Potential_Score"),
              valueBoxOutput("Multi_species"),
              valueBoxOutput("Multi_omics"),
              
              column(
                width = 12,class = "text-center",
                box(status = "primary",
                  plotOutput("123", width = "380px", height = "360px") %>% withSpinner(color = "#EA2027"),
                  title = "123",
                  width = 4
                ),
                box(status = "warning",
                  plotOutput("456", width = "400px", height = "360px") %>% withSpinner(color = "#EE5A24"),
                  title = "456",
                  width = 4
                ),
                box(status = "success",
                  plotOutput("789", width = "350px", height = "360px") %>% withSpinner(color = "#F79F1F"),
                  title = "789",
                  width = 4
                ),
              ))
            )
              
            ))
    
  )

`
Any advice would be greatly appreciated!

**Comment by PaulC91** [comment]
Hi. 

The userbase data is just displayed for example purposes, you don't need to include it in your app.

Github issues are usually reserved for raising package bugs or feature requests. If you need help with your coding please post your problem on [stackoverflow](https://stackoverflow.com/) or [Posit Community](https://community.rstudio.com/). 

Good luck!
