### ISSUE TITLE
Cases for help

### ISSUE THREAD

**Issue by korterling** [PaulC91/shinyauthr#65]
Dear Paul, your package is really great, I'm learning this package, I saw that you gave several cases, but I'm currently using tinyMobile (https://github.com/RinteRface/shinyMobile),  I tried many times, but did not succeed, can you give a simple case with shinyMobile,thank you very much!

**Comment by korterling** [comment]
@PaulC91

**Comment by PaulC91** [comment]
Hi @korterling, sorry I won't have time to make a case with that UI framework in the near future. I suggest you post your problem on the [Posit community forum](https://community.rstudio.com/) or [stackoverflow](https://stackoverflow.com/) where I'm sure the R community will be happy to help. Thanks!
